Document: snow
Title: Debian snow Manual
Author: <insert document author here>
Abstract: This manual describes what snow is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/snow/snow.sgml.gz

Format: postscript
Files: /usr/share/doc/snow/snow.ps.gz

Format: text
Files: /usr/share/doc/snow/snow.text.gz

Format: HTML
Index: /usr/share/doc/snow/html/index.html
Files: /usr/share/doc/snow/html/*.html
